<a href="https://colab.research.google.com/github/gaojing33/Stat-Data-Science/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [9]:
df = pd.read_excel('Envtaxpercountries.xlsx')

In [11]:
print(df)

            Country      2014      2015      2016      2017      2018  \
0             Malta    129.49    135.66    146.81    154.52    158.72
1   North Macedonia    128.49    146.03    161.65    166.68    194.94
2            Cyprus    405.74    425.78    435.33    475.87    481.20
3           Estonia    463.78    491.27    567.28    599.29    623.73
4         Lithuania    580.49    622.94    677.26    731.92    809.33
5            Latvia    677.80    730.58    784.27    807.95    849.28
6        Luxembourg    904.87    871.23    852.67    876.01    952.20
7          Bulgaria   1068.66   1192.28   1267.38   1281.28   1264.27
8           Croatia   1003.82   1126.25   1220.49   1289.47   1418.03
9          Slovenia   1223.29   1271.13   1330.91   1335.25   1305.18
10         Slovakia   1693.76   1762.18   1773.70   1897.15   1965.03
11          Hungary   1944.16   2085.12   2237.87   2323.93   2321.87
12          Ireland   2840.20   3042.88   3135.26   3258.00   3176.04
13          Romania   3183.94   3540.75   3674.13   3372.24   3743.06
14          Czechia   3103.17   3217.57   3465.15   3621.55   3841.35
15         Portugal   2878.61   3185.49   3531.93   3640.18   3800.02
16          Finland   4003.81   4170.31   4543.36   4480.33   4639.81
17           Norway   4777.84   4572.94   4492.82   4711.91   4960.15
18          Austria   5023.85   5216.40   5284.47   5539.72   5385.30
19          Denmark   6167.01   6023.80   6134.53   5879.36   5894.07
20      Switzerland   5115.14   5912.00   6095.44   6035.23   6150.91
21           Greece   5961.00   6030.00   5891.00   6319.00   5929.00
22           Sweden   7310.33   7426.20   7773.66   7603.66   7094.10
23          Belgium   6948.80   7262.80   8082.60   8537.30   8820.80
24           Poland   9107.85   9764.82   9996.33  10889.12  11788.80
25      Netherlands  12608.00  12788.00  13362.00  13691.00  14487.00
26            Spain  16103.00  17389.00  17202.00  17693.00  18253.00
27           France  34087.00  37987.00  40738.00  43426.00  45791.00
28            Italy  47860.00  45512.00  48393.00  46868.00  47128.00
29          Germany  48672.22  48537.57  48241.12  49795.22  50721.11

        2019      2020      2021      2022
0     178.63    141.59    137.55    144.55
1     200.24    188.50    205.04    184.08
2     459.25    396.12    440.10    423.55
3     817.05    601.64    662.62    758.02
4     836.77    867.15    919.38    873.51
5     791.85    792.87    790.90    687.60
6    1009.55    816.39    980.56    871.95
7    1626.96   1642.08   1743.98   3858.47
8    1468.37   1264.46   1418.51   1385.02
9    1516.79   1270.40   1380.54   1373.92
10   2099.75   2068.22   2153.40   1951.70
11   2507.15   2279.36   2347.79   1942.81
12   3015.24   2767.86   3200.65   2614.56
13   4408.93   3878.69   4343.47   4121.21
14   4301.44   3880.70   4119.89   3940.73
15   3919.59   3563.61   3848.41   3348.83
16   4688.51   4605.24   4685.94   4897.80
17   4705.97   4249.92   5075.91   5415.64
18   5568.59   4611.44   5310.58   4793.51
19   5285.10   5163.15   5206.98   5174.43
20   6394.63   6285.60   6571.19   7050.74
21   6186.00   5418.00   6213.00   9932.00
22   7070.35   7021.69   5038.61   4285.58
23   8961.60   7958.70   8894.70   8593.10
24  11787.51  11711.97  15027.38  16705.58
25  15793.00  14318.00  15189.00  11249.00
26  18077.00  16016.00  17319.00  16555.00
27  45798.00  40773.00  44686.00  42335.00
28  47127.00  40353.00  43631.00  33893.00
29  50906.42  47786.25  58152.90  56054.31